config/routes.rb
Parties::Application.routes.draw do
  root to: 'home#index'
  get 'home/pirate1'
  get 'home/pirate2'
  get 'home/pirate3'
  get 'home/jack'
  get 'home/without_pirate'

  resources :parties, only: %i[new show update], path: '' do
    collection do
      post '/parties' => :create, as: ''
    end
  end

  post '/settings', to: 'participants#set', as: :settings
  post '/participants', to: 'participants#create', as: :participants
  post '/items', to: 'items#create', as: :items
  delete '/items/:id', to: 'items#destroy', as: :item

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :party
  has_and_belongs_to_many :participants
  attr_accessible :name
  validates_presence_of :name
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :party
  has_and_belongs_to_many :items
  attr_accessible :name
  validates_presence_of :name
  validates_uniqueness_of :name, scope: :party_id

  def short_name
    splitted = name.split ' '
    splitted.many? ? splitted.first(2).map{|w| w[0]}.join.upcase : name[0..1].downcase.capitalize
  end

  def color
    name.to_s(16).first(6)
  end

end

app/models/party.rb
class Party < ActiveRecord::Base
  extend FriendlyId
  has_many :participants
  has_many :items
  friendly_id :name, use: [:slugged, :history]
  attr_accessible :description, :location, :name, :slug, :start_at, :items_attributes
  accepts_nested_attributes_for :items
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = Item.new(params[:item])
    @item.party_id = params[:party][:id]

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to parties_url }
      format.json { head :no_content }
      format.js
    end
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def set
    @participant = Participant.includes(:items).where(party_id: params[:party][:id]).find(params[:participant][:id])
    @items = Party.find(params[:party][:id]).items

    respond_to do |format|
      if @participant.items = Item.where(id: (params[:items] || {}).keys)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @participant = Participant.new(params[:participant])
    @participant.party_id = params[:party][:id]

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render json: @participant, status: :created }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_filter :find_party, only: [:show, :edit]

  # GET /1
  # GET /1.json
  def show
  end

  # GET /new
  # GET /new.json
  def new
    @party = Party.new
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(params[:party])

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render json: @party, status: :created, location: @party }
      else
        format.html { render action: "new" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /1
  # PUT /1.json
  def update
    @party = Party.find(params[:id])

    respond_to do |format|
      if @party.update_attributes(params[:party])
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /1
  # DELETE /1.json
  def destroy
    @party = Party.find(params[:id])
    @party.destroy

    respond_to do |format|
      format.html { redirect_to parties_url }
      format.json { head :no_content }
    end
  end

  private

  def find_party
    @party = Party.find(params[:id])

    if request.path != party_path(@party)
      redirect_to @party, status: :moved_permanently
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/home/index.html.haml
.jumbotron
  %h1 ibring.me

  %p Shared grocery lists for events.

  %i.icon.checklist

  = link_to 'Create a list', new_party_path, class: 'btn btn-primaty btn-large'

app/views/items/_show.html.haml
%label.checkbox{ class: "iid_#{i.id}" }
  = check_box_tag "items[#{i.id}]", 1, defined?(checked) ? checked : false, class: 'item', 'data-id' => i.id
  %p.item_name= i.name
  - if i.participants.empty?
    = link_to i, method: :delete, remote: true do
      .participant.delete{ title: 'Delete', class: 'touriste' } –
  - i.participants.each do |p|
    = render 'participants/avatar', p: p

app/views/items/create.js.erb
$('.items').append("<%= escape_javascript(render 'show', i: @item) %>");
$('#item_name').val('');

app/views/items/destroy.js.erb
$('.iid_<%= @item.id %>').remove();

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) + ' - ' + t('.title') : t('.title')
    = stylesheet_link_tag :application, :media => "all"
    = csrf_meta_tags
    = yield :head
  %body{ class: [controller_name, action_name]}
    = yield :header
    #container.container
      = render 'layouts/messages'
      = content_for?(:content) ? yield(:content) : yield
    = javascript_include_tag :application
    = yield :js

app/views/layouts/parties.html.haml
-content_for :content do
  %header.pull-right
    =link_to root_path do
      %h1 ibring.me
      .catchphrase Shared grocery lists for events
  =yield

=render template: 'layouts/application'

app/views/participants/_avatar.html.haml
.participant{ title: p.name, 'data-id' => p.id, 'data-items' => p.items.map(&:id), class: p.items.any? ? '' : 'touriste' }= p.short_name

app/views/participants/create.js.erb
$('.participants').append("<%= escape_javascript(render 'avatar', p: @participant) %>");
$('.participant[data-id=<%= @participant.id %>]').tooltip().click();
$('#participant_name').val('');

app/views/participants/set.js.erb
$items = $('.items');
$items.html('')
<% @items.each do |i| %>
  $items.append("<%= escape_javascript(render 'items/show', i: i, checked: @participant.items.include?(i)) %>");
<% end %>
$('.participant').tooltip();

app/views/parties/_form.html.haml
= simple_form_for(@party, html: { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/parties/_item_fields.html.haml
.nested-fields.form-inputs
  = link_to_remove_association "remove item", f
  = f.input :name

app/views/parties/new.html.haml
.clearfix.visible-phone
%h1.top Create your event

#CreatorWizard.fuelux-wizard.wizard
  .header
    %ol.steps

      %li{"data-target" => "#step1"}
        %span Your event
      %li{"data-target" => "#step2"}
        %span Some supplies
      %li{"data-target" => "#step3"}
        %span Your guests

  .widget
    = simple_form_for(@party, html: { class: 'form-horizontal step-content' }) do |f|
      = f.error_notification
      #step1.step-pane
        .form-inputs
          = f.input :name
          = f.input :location
          = f.input :start_at, :as => :datepicker
          = f.input :description, input_html: { rows: 3 }
        .pull-right
          %a.btn.btn-large.btn-next{:href => "#", "data-target" => "#step2"}
            next
            %i.icon-arrow-right
        .clearfix
      #step2.step-pane
        .templates.pull-right
          %a.btn.btn-template{:href => "#templatesModal", "data-toggle" => "modal"}
            %i.icon-bookmark
            ideas
        .items
          = f.simple_fields_for :items do |i|
            = render 'item_fields', :f => i
          .links
            .control-group.form-inputs
              %label.control-label
              .controls
                %input{:type => "text",:disabled => ""}
            = link_to_add_association 'Add item', f, :items
            .clearfix
        .pull-right
          %a.btn.btn-large.btn-next{:href => "#", "data-target" => "#step3"}
            next
            %i.icon-arrow-right
        .clearfix
        #templatesModal.modal.hide.fade
          .modal-header
            %button.close{"data-dismiss" => "modal", :type => "button"} ×
            %h3#myModalLabel Choose a template
          .modal-body
            %p
          .modal-footer
            %button.btn{"data-dismiss" => "modal"} Close
      #step3.step-pane
        .form-inputs
          .control-group
            %label.control-label Destinataires
            .controls
              = text_area :post, :body, :rows => 3
        .pull-right
          = f.button :submit, class: 'btn btn-large'
        .clearfix


- content_for :js do
  :javascript
    (function(){
      var $step2 = $('#step2');
      var $tmplModal = $('#templatesModal');
      var gblTemplate;
      var gblSuggestions;

      $('#CreatorWizard').wizard();
      $step2.itemlist();

      if($step2.find('.nested-fields').length == 0){$step2.find('.add_fields').click();}

      // load templates in modal
      $.getJSON('template.json', function(data) {
        gblTemplate = data;
        $tmplList = $tmplModal.find('.modal-body p');
        for(var i in gblTemplate){
          var template = gblTemplate[i];
          
          $tmplList.append('<div class="span2"><label class="template" for="'+template.name+'"  data-dismiss="modal">'+
                            '<div class="thumbnail">'+
                            '<div class="caption">'+(template.image?'<img src="'+template.image+'" />':'')+
                            '<h3>'+(template.label || template.value)+'</h3><p>'+template.desc+'</p>'+
                            '</div></label></div>');
        }
      });

      $.getJSON('suggestions.json', function(data) {
        gblSuggestions = data;
      });

      // add templates items
      $tmplModal.on('click', 'label.template', function(){
        var $elt = $(this);
        for(var i in gblTemplate){
          var template = gblTemplate[i];
          if(template.name === $elt.attr('for')){
            $step2.itemlist('add-items', template.items);
            $elt.attr('checked', false);
            break;
          }
        }
      });

      function getSuggestion(suggestionName){
        if(gblSuggestions){
          for(var i in gblSuggestions){
            if(gblSuggestions[i].value == suggestionName){
              return gblSuggestions[i];
            }
          }
        }
      }

      function setQuickAction(selectedObj){
        console.log(selectedObj);
        $step2.find('.links .quick-action').remove();
        if(selectedObj && selectedObj.next && selectedObj.next.length > 0){
          var $addField = $step2.find('.links .add_fields');
          for(var i in selectedObj.next){
            var nextElt = selectedObj.next[i];
            $addField.after('<a href="#" class="quick-action">add <span>'+nextElt+'</span> ?</a>');
          }
          // add suggested actions
          $step2.find('.links .quick-action').click(function(){
            var itemToAdd = $(this).find('span').html();
            $step2.itemlist('add-items', [itemToAdd]);
            setQuickAction(getSuggestion(itemToAdd));
            $(this).remove();
            return false;
          });
        }
      }

      // watch which item is selected
      $step2.bind('typeahead:selected', function(event, selectedObj){
        setQuickAction(selectedObj);
      });
    }).call(this);

app/views/parties/show.html.haml
- content_for :title, @party.name

%h1= best_in_place @party, :name
%p= best_in_place @party, :start_at, type: :date
%p= best_in_place @party, :description, nil: t('.description')

.widget
  = form_tag participants_path(format: :js), remote: true, class: 'form-horizontal form-participants' do
    = hidden_field_tag "party[id]", @party.id
    .control-group
      %label.control-label Subscribe as
      .controls
        .input-append
          = text_field_tag 'participant[name]'
          = submit_tag '+', class: 'btn'
    .control-group
      %label.control-label Participants
      .controls
        .participants
          - @party.participants.includes(:items).each do |p|
            = render 'participants/avatar', p: p
        - if @party.participants.any?
          .help-block Click to see what the participant brings

.widget
  = form_tag settings_path(format: :js), remote: true, class: 'form-horizontal form-items' do
    = hidden_field_tag "party[id]", @party.id
    = hidden_field_tag "participant[id]", 0
    .control-group
      %label#stuff.control-label Stuff you bring
      .controls
        .items
          - @party.items.includes(:participants).each do |i|
            = render 'items/show', i: i
  = form_tag items_path(format: :js), remote: true, class: 'form-horizontal form-add-item' do
    = hidden_field_tag "party[id]", @party.id
    .control-group
      .controls
        .input-append
          = text_field_tag 'item[name]'
          = submit_tag '+', class: 'btn'